# Site settings
title: insert(self)
header-img: img/home-bg.png
email: hilyttle@gmail.com
copyright_name: hilaryml
description: > # this means to ignore newlines until "baseurl:"
  A coding blog.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hilaryml
learn_profile: hilaryml
email_username: hilyttle@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
